ports:
- port: 8081
  onOpen: open-preview
- port: 3000
  onOpen: open-preview
- port: 18081
  onOpen: ignore
- port: 5005
  onOpen: ignore
tasks:
# - command: npm install -g npm &&
#    npm install -g yo &&
#    npm install -g generator-jhipster
#- command: cd jhipster-api-service && _JAVA_OPTIONS="-Xmx750M" ./mvnw
- command: cd docs/ && npm install && node express.js
- command: open /workspace/api-toolset-presentation-and-workshop/jhipster-api-service/src/main/resources/swagger/productapi.yml &&
        open /workspace/api-toolset-presentation-and-workshop/jhipster-api-service/pom.xml &&
        open /workspace/api-toolset-presentation-and-workshop/jhipster-api-service/src/test/resources/contracts/productcontract.yml &&
        cd /workspace/api-toolset-presentation-and-workshop/jhipster-api-service/
# - command: gp preview $(gp url 8081)
# - init: wget http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.23.2/wiremock-standalone-2.23.2.jar -P /workspace/api-toolset-presentation-and-workshop/wiremock
